repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^templates/templated_email/compiled/
        exclude_types: [svg,graphql]
      - id: end-of-file-fixer
        exclude: ^templates/templated_email/compiled/
        exclude_types: [svg]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.222
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.3
    hooks:
      - id: pydocstyle
        files: ^saleor/
        exclude: tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        language: system
        exclude: tests/

  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "./manage.py makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [commit]

  - repo: local
    hooks:
      - id: gql-schema-check
        language: system
        name: Check GraphQL schema is up to date.
        entry: sh -c "./manage.py get_graphql_schema | diff saleor/graphql/schema.graphql -"
        stages: [commit]
